### ISSUE TITLE
Why is the browser plugin archived?

### ISSUE THREAD

**Issue by Elyx0** [networkprotocol/netcode#101]
Just curious I come from the blog article, is it dropped?

**Comment by gafferongames** [comment]
I guess the author didn't want to work on it anymore

**Comment by ben-xD** [comment]
The premise of netcode is easy but fast networking for games on browsers, but the browser implementation is archived.

It seems like the reason for netcodes existence is gone? Am I misunderstanding something?

Now netcode has pivoted to networking for games in general, excluding web games?
