### ISSUE TITLE
[Question] Connect Token private part

### ISSUE THREAD

**Issue by hojjatjafary** [networkprotocol/netcode#108]
Hi,

If I understand the protocol correctly there is no connection between Web backend and Game server so the client should pass some data in the encrypted part of connect token to game server.

The game server can be initialized with the information from web backend, the keys, the allowed players to connect and an associated connection ticket, with the ticket it can reject all other connection requests.

So we can replace the encrypted part with the connection ticket that is a random string data, and we can find player information with the corresponding connection ticket.

What is the reason that the protocol does not consider a simple web request from game server to web backend to get such initialization data?

Thanks.

**Comment by gafferongames** [comment]
The idea is that you already have your own backend (eg. matchmaker), and on this matchmaker -- you generate the token and pass it down to the client. Therefore, only clients that are authorized to connect to the server by the matchmaker are allowed in.

cheers
