### ISSUE TITLE
[Question] Is it possible to handle direct IP connections without a matchmaker service?

### ISSUE THREAD

**Issue by Kazade** [networkprotocol/netcode#109]
:wave: 

This is probably a case of me using netcode for the wrong situation but we'll see...

I'm developing a game that ideally would have a matchmaker service, but for redundancy (or.. if I run out of time) I'd quite like players to be able to host a game, and enter an IP address to direct connect to that server. This was working fine for testing on localhost.. but not across a network...

The problem I've hit is that the server needs to know its own external IP address when validating the connect token.. is there a way to avoid that? Would it be dangerous to disable that check in the direct connection case? (Ignoring the fact that I've probably blown any security out of the water anyway by shipping the private key in the client side but I'd use a separate key for direct connecting...)

**Comment by gafferongames** [comment]
Unfortunately, no we don't support that. Sorry!
